id: I1B4FDD84
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:10:26+00:00'
last_modified: '2022-06-08T06:40:17.537806+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3990
  title: མཁས་པའི་ཚུལ་ལ་འཇུག་པའི་སྒོ་ཞེས་བྱ་བའི་བསྟན་བཅོས་དང་མཁས་འཇུག་གི་སྡོམ་བྱང་དང་ས་བཅད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0A72:
      image_group_id: I1KG4052
      title: ''
      total_pages: 428
      order: 1
      base_file: 0A72.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
